[package]
name = "paxos"
version = "0.1.0"
edition = "2021"

[dependencies]
all_asserts = "2.3.3"
clap = { version = "4.5.32", features = ["derive"] }
ctrlc = "3.4.5"
itertools = "0.14.0"
log = "0.4.26"
rand = "0.9.0"
simple_logger = "5.0.0"
